### ISSUE TITLE
singlet.gate doesn't seem to be mentioned anywhere except the docs

### ISSUE THREAD

**Issue by nicbarker** [mehrnoushmalek/flowDensity#1]
Hi,
In the vignettes, there is an example that mentions the following:
```R
sglt <- flowDensity(obj=lymph, singlet.gate=TRUE)
```
On my machine, this throws an error:

```R
> sglt <- flowDensity(obj=lymph, singlet.gate=TRUE)
Error in (function (classes, fdef, mtable)  :
  unable to find an inherited method for function ‘flowDensity’ for signature ‘"CellPopulation", "missing", "missing", "missing"’
```

When I grep the codebase, there doesn't seem to be any mention of `singlet.gate` except for in the documentation.

Is there something I'm missing here?

**Comment by mehrnoushmalek** [comment]
I got rid of songlet.gate, but haven't had time to update the man page.
I'm away, but will look into it first thing next week.

**Comment by nicbarker** [comment]
Thanks for the tip! This isn't the highest priority issue, just thought I'd point it out.
