### ISSUE TITLE
Remove empty commits from the history

### ISSUE THREAD

**Issue by nicbarker** [mehrnoushmalek/flowDensity#3]
Hi,
It seems like there's a large number of empty commits in the history of this repository that may have been imported from another VCS like mercurial or something.

I've created a fork that has removed all of the empty commits (i.e. commits with no changes) -
 there is 102 / ~40,000 left over. You can see here:

https://github.com/nicbarker/flowDensity

For me at least, it helps a lot to be able to track the history of changes to the algorithm without having to sift through a large number of empty commits.

Let me know what you think.

**Comment by mehrnoushmalek** [comment]
I don't understand what you mean by empty commits.
I just recently updated the bioconductor GitHub to see if everything is updated and I made a comment about that commit.
It seems that so many people from Bioconductor side tried to update, or change things as well, so I had many conflicts when I was trying to commit my changes.

**Comment by nicbarker** [comment]
Hi,
What I mean by empty commits is a commit that doesn't change any files.
Here's a recent example:
https://github.com/mehrnoushmalek/flowDensity/commit/25968ab2cc3a4c6f3b55892be1f0fc94deb10b2f
Given that the commit message is `Minor code cleanup; make it possible to keep chromosomes without any targets (for off-target coverage).` it sounds like this commit was pulled in from a different (probably sequencing related) repository.
If you take a look at my branch, I've filtered out all the commit that don't have any changes, which is over 99% of them:
https://github.com/nicbarker/flowDensity/commits/master

**Comment by mehrnoushmalek** [comment]
It seems that there are tons of commits from people I don't know. I'd get in touch with bioconductor people to see what's wrong.
