### ISSUE TITLE
plotDens not working with GatingHierarchy

### ISSUE THREAD

**Issue by osthomas** [mehrnoushmalek/flowDensity#5]
Hi,

plotDens is not working correctly with a GatingHierarchy object, because the class check falls through to the default case.

Changing https://github.com/mehrnoushmalek/flowDensity/blob/cec850f4a84e8edfb813c12e8841e04307b6a653/R/flowDensity_methods.R#L135 

to `else if(class(obj)=="CellPopulation")` fixes this.

**Comment by mehrnoushmalek** [comment]
Thanks for checking @osthomas. It's fixed now.
